export * from './user.model';
export * from './patient.model';
export * from './professional.model';
export * from './appointment.model';
export * from './budget.model';
export * from './file.model';
export { MedicalRecord, MedicalRecordCreate } from './medical-record.model';
export { MedicalFile as MedicalRecordFile, FileUpload as MedicalRecordFileUpload } from './medical-record.model';
export * from './odontology.model';
export * from './psychology.model';
export * from './psychopedagogy.model';
export * from './report.model';
