"""Add odontology models (odontograms, teeth, dental_treatments)

Revision ID: 6f4e7b8121ff
Revises: ed502dcd95d9
Create Date: 2025-11-22 02:52:00.180379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4e7b8121ff'
down_revision: Union[str, None] = 'ed502dcd95d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odontograms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teeth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odontogram_id', sa.Integer(), nullable=False),
    sa.Column('tooth_number', sa.Integer(), nullable=False),
    sa.Column('tooth_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('mesial', sa.String(length=50), nullable=True),
    sa.Column('distal', sa.String(length=50), nullable=True),
    sa.Column('oclusal', sa.String(length=50), nullable=True),
    sa.Column('vestibular', sa.String(length=50), nullable=True),
    sa.Column('lingual', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.String(length=50), nullable=True),
    sa.Column('mobility', sa.Integer(), nullable=True),
    sa.Column('gingival_status', sa.String(length=50), nullable=True),
    sa.Column('pocket_depth', sa.Integer(), nullable=True),
    sa.Column('planned_treatment', sa.String(length=200), nullable=True),
    sa.Column('treatment_priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odontogram_id'], ['odontograms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odontogram_id', 'tooth_number', name='unique_tooth_per_odontogram')
    )
    op.create_table('dental_treatments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('medical_record_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('treatment_code', sa.String(length=50), nullable=True),
    sa.Column('treatment_type', sa.String(length=100), nullable=False),
    sa.Column('affected_teeth', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('materials_used', sa.JSON(), nullable=True),
    sa.Column('technique', sa.String(length=200), nullable=True),
    sa.Column('anesthesia_type', sa.String(length=100), nullable=True),
    sa.Column('anesthesia_details', sa.String(length=200), nullable=True),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sessions_required', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('next_appointment', sa.Date(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('final_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_covered', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('patient_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pre_treatment_notes', sa.Text(), nullable=True),
    sa.Column('post_treatment_notes', sa.Text(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('medications_prescribed', sa.JSON(), nullable=True),
    sa.Column('patient_satisfaction', sa.Integer(), nullable=True),
    sa.Column('treatment_success', sa.Boolean(), nullable=True),
    sa.Column('requires_followup', sa.Boolean(), nullable=True),
    sa.Column('followup_date', sa.Date(), nullable=True),
    sa.Column('followup_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dental_treatments')
    op.drop_table('teeth')
    op.drop_table('odontograms')
    # ### end Alembic commands ###
