"""add_index_to_appointment_created_at

Revision ID: 982138921831
Revises: 63f140c09d89
Create Date: 2026-02-21 23:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982138921831'
down_revision: Union[str, None] = '63f140c09d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_created_at'), 'appointments', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_created_at'), table_name='appointments')
    # ### end Alembic commands ###
