"""Initial migration

Revision ID: ed502dcd95d9
Revises: 
Create Date: 2025-11-22 01:37:44.847918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed502dcd95d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_patient_date', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.create_index('idx_professional_date', 'appointments', ['professional_id', 'appointment_date'], unique=False)
    op.create_index('idx_status_date', 'appointments', ['status', 'appointment_date'], unique=False)
    op.create_index('idx_patient_record_date', 'medical_records', ['patient_id', 'record_date'], unique=False)
    op.create_index('idx_professional_record_date', 'medical_records', ['professional_id', 'record_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_professional_record_date', table_name='medical_records')
    op.drop_index('idx_patient_record_date', table_name='medical_records')
    op.drop_index('idx_status_date', table_name='appointments')
    op.drop_index('idx_professional_date', table_name='appointments')
    op.drop_index('idx_patient_date', table_name='appointments')
    # ### end Alembic commands ###
